{{/*
Autor:   Diego Regis M. F. dos Santos
Email:   diego-f-santos@openlabs.com.br
Time:    OpenLabs - DevOps | Infra
Versão:  2.0.0
Arquivo: helm/status-report/templates/secret.yaml
*/}}

{{/* Secret SMTP — criado apenas se não usar existingSecret */}}
{{- if not .Values.smtp.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "status-report.fullname" . }}-smtp
  namespace: {{ include "status-report.namespace" . }}
  labels:
    {{- include "status-report.labels" . | nindent 4 }}
type: Opaque
stringData:
  smtp-user:     {{ .Values.smtp.user | quote }}
  smtp-password: {{ .Values.smtp.password | quote }}
{{- end }}
{{/* Secret Webhooks — Teams e Slack */}}
{{- if not .Values.teams.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "status-report.fullname" . }}-webhooks
  namespace: {{ include "status-report.namespace" . }}
  labels:
    {{- include "status-report.labels" . | nindent 4 }}
type: Opaque
stringData:
  teams-webhook-url: {{ .Values.teams.webhookUrl | quote }}
  slack-webhook-url: {{ .Values.slack.webhookUrl | quote }}
{{- end }}
