{{/*
Autor:   Diego Regis M. F. dos Santos
Email:   diego-f-santos@openlabs.com.br
Time:    OpenLabs - DevOps | Infra
Versão:  2.0.0
Arquivo: helm/status-report/templates/serviceaccount.yaml
*/}}
{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "status-report.serviceAccountName" . }}
  namespace: {{ include "status-report.namespace" . }}
  labels:
    {{- include "status-report.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: true
{{- end }}
